### ISSUE TITLE
Need to Add a reference to CoreFTP software to the file-transfer page since it is an MCW sponsored package.

### ISSUE THREAD

**Issue by Bill-Branson** [mcw-rcc/mcw-rcc.github.io#26]
### What should we edit?

NOTE:  Add CoreFTP reference to https://docs.rcc.mcw.edu/storage/file-transfer/

**Comment by maflister** [comment]
Agreed. Should add a reference to MobaXterm as well since it has built-in SFTP client.

**Comment by maflister** [comment]
@Bill-Branson something like this? #27
